Repository google-gemini/gemini-cli, pull requests merged in 2025-09, with the labels that each got.

#7368 fix(ide): use port number for server port file instead of vscode pid
  packages/vscode-ide-companion/NOTICES.txt
  packages/vscode-ide-companion/src/ide-server.test.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: kind/bug, priority/p2, area/extensibility

#7566 refactor(core): Require model for utility calls
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/tools/web-fetch.ts
  packages/core/src/tools/web-search.ts
Labels: status/need-issue

#7364 Support installing extensions with org/repo
  packages/cli/src/commands/extensions/install.test.ts
  packages/cli/src/commands/extensions/install.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7420 Fix(cli) - Remove Foldertrust Feature Flag
  docs/cli/configuration.md
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/config/trustedFolders.test.ts
  packages/cli/src/config/trustedFolders.ts
  packages/cli/src/ui/hooks/useFolderTrust.ts
Labels: status/need-issue

#7419 Add footer configuration settings
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/__snapshots__/App.test.tsx.snap
  packages/cli/src/ui/components/Footer.test.tsx
  packages/cli/src/ui/components/Footer.tsx
  packages/cli/src/ui/components/MemoryUsageDisplay.tsx
Labels: kind/bug, kind/enhancement, priority/p2, area/ux, maintainer

#7614 feat(quality): Skip the next speaker check by default
  packages/cli/src/config/settingsSchema.ts
Labels: area/models, maintainer

#7601 chore(ci): Update GitHub /assign workflow to use advanced search API
  .github/workflows/gemini-self-assign-issue.yml
Labels: status/need-issue

#7621 Rename smart_edit to replace to align with the EditTool
  packages/core/src/tools/smart-edit.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7162 feat(cli): Add support for Ctrl+Backspace to delete a word backward
  packages/cli/src/config/keyBindings.ts
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/components/shared/text-buffer.ts
  packages/cli/src/ui/contexts/KeypressContext.test.tsx
  packages/cli/src/ui/keyMatchers.test.ts
Labels: kind/bug, good first issue, priority/p2, area/ux, maintainer

#7599 chore(e2e): Stabilize e2e test by adding a more descriptive prompt
  integration-tests/utf-bom-encoding.test.ts
Labels: status/need-issue

#7555 fix: gemini-cli-vscode-ide-companion's package script
  package-lock.json
  packages/vscode-ide-companion/package.json
  scripts/build_vscode_companion.js
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7593 chore(a2a-server): refactor a2a-server src directory
  packages/a2a-server/package.json
  packages/a2a-server/src/agent/executor.ts
  packages/a2a-server/src/agent/task.test.ts
  packages/a2a-server/src/agent/task.ts
  packages/a2a-server/src/config/config.ts
  packages/a2a-server/src/config/extension.ts
  packages/a2a-server/src/config/settings.ts
  packages/a2a-server/src/http/app.test.ts
  packages/a2a-server/src/http/app.ts
  packages/a2a-server/src/http/endpoints.test.ts
  packages/a2a-server/src/http/requestStorage.ts
  packages/a2a-server/src/http/server.ts
  packages/a2a-server/src/index.ts
  packages/a2a-server/src/persistence/gcs.test.ts
  packages/a2a-server/src/persistence/gcs.ts
  packages/a2a-server/src/utils/logger.ts
  packages/a2a-server/src/utils/testing_utils.ts
Labels: priority/p3, kind/cleanup, area/contribution

#7605 Move settings error throwing to loadSettings
  packages/cli/src/commands/mcp/add.ts
  packages/cli/src/commands/mcp/list.ts
  packages/cli/src/commands/mcp/remove.ts
  packages/cli/src/config/auth.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/settings.test.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/gemini.test.tsx
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/components/AuthDialog.test.tsx
  packages/cli/src/ui/components/SettingsDialog.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/utils/userStartupWarnings.ts
Labels: kind/bug, priority/p1, area/core, maintainer

#7666 Fix(core): Log exact model version from API response
  packages/core/src/core/loggingContentGenerator.ts
Labels: status/need-issue

#7674 fix(core): Fix more logging issues
  packages/core/src/core/loggingContentGenerator.ts
Labels: status/need-issue

#7676 fix(tests): make read_many_files test more reliable
  integration-tests/read_many_files.test.ts
Labels: status/need-issue

#7539 fix(auth): improve Google OAuth error handling and prevent empty error messages
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
Labels: kind/bug, area/authentication

#7609 Fix diff approval race between CLI and IDE
  packages/core/src/ide/ide-client.ts
Labels: kind/bug, priority/p1, area/extensibility

#6564 Add enforcedAuthType setting
  docs/cli/configuration.md
  docs/cli/enterprise.md
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/AuthDialog.test.tsx
  packages/cli/src/ui/components/AuthDialog.tsx
  packages/cli/src/validateNonInterActiveAuth.test.ts
  packages/cli/src/validateNonInterActiveAuth.ts
Labels: area/authentication, priority/p2, area/core, maintainer

#7668 feat: Add positional argument for prompt
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: kind/enhancement, area/core, maintainer

#7679 Enable smart edit by default on main
  packages/core/src/config/config.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.test.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7408 feat(extension) - Notify users when there is a new version and update it
  packages/vscode-ide-companion/src/extension.test.ts
  packages/vscode-ide-companion/src/extension.ts
Labels: good first issue, sub-area/extensions, maintainer

#7445 refactor(setting): Improve settings migration and tool loading
  packages/cli/src/config/settings.test.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/utils/deepMerge.test.ts
  packages/cli/src/utils/deepMerge.ts
  packages/core/src/config/config.test.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-issue, status/need-retesting

#7577 rename(telemetry): Update ai_(added|removed)_lines to model_(added|removed)_lines
  docs/telemetry.md
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/types.ts
  packages/core/src/telemetry/uiTelemetry.test.ts
  packages/core/src/telemetry/uiTelemetry.ts
  packages/core/src/tools/diffOptions.test.ts
  packages/core/src/tools/diffOptions.ts
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/tools.ts
Labels: kind/enhancement, maintainer

#7740 Takethree
  integration-tests/read_many_files.test.ts
  package-lock.json
  package.json
  packages/a2a-server/package.json
  packages/cli/package.json
  packages/cli/src/config/settings.test.ts
  packages/cli/src/config/settings.ts
  packages/core/package.json
  packages/test-utils/package.json
  packages/vscode-ide-companion/package.json
Labels: status/need-issue

#7716 Feat(security) - Make the OAuthTokenStorage non static
  packages/cli/src/ui/commands/mcpCommand.test.ts
  packages/cli/src/ui/commands/mcpCommand.ts
  packages/core/src/mcp/oauth-provider.test.ts
  packages/core/src/mcp/oauth-provider.ts
  packages/core/src/mcp/oauth-token-storage.test.ts
  packages/core/src/mcp/oauth-token-storage.ts
  packages/core/src/tools/mcp-client.ts
Labels: status/need-issue

#7752 fix: Remove 'node-fetch' from externals
  esbuild.config.js
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7174 fix(ui): fix drag-and-drop file feature for macOS terminal 2
  packages/cli/src/ui/contexts/KeypressContext.test.tsx
  packages/cli/src/ui/contexts/KeypressContext.tsx
Labels: kind/bug, status/need-triage

#7703 Fix dollar sign replacement bug in file editing
  integration-tests/replace.test.ts
  packages/a2a-server/src/agent/task.ts
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/smart-edit.test.ts
  packages/core/src/tools/smart-edit.ts
Labels: kind/bug, priority/p2, status/need-information, area/ux

#7765 feat(triage): add status/bot-triaged label after triage
  .github/workflows/gemini-automated-issue-triage.yml
  .github/workflows/gemini-scheduled-issue-triage.yml
Labels: status/need-issue

#7745 Feat(security) - Create a class for Oauth credential
  packages/core/src/code_assist/oauth-credential-storage.test.ts
  packages/core/src/code_assist/oauth-credential-storage.ts
  packages/core/src/config/storage.ts
Labels: status/need-issue

#7647 fix the proQutaDialog
  packages/cli/src/ui/App.tsx
Labels: kind/bug, priority/p2, area/ux

#7807 Make 'source' a positional argument in extensions install and set flag to true
  packages/cli/src/commands/extensions/install.test.ts
  packages/cli/src/commands/extensions/install.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/ui/hooks/useWorkspaceMigration.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7817 Add initial RFC for A2A development-tool extension
  packages/a2a-server/development-extension-rfc.md
Labels: status/need-issue

#7797 Add hidden property to slash commands
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/ui/commands/corgiCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/components/Help.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/useSlashCompletion.ts
  packages/core/src/core/contentGenerator.test.ts
Labels: kind/enhancement, area/ux

#7759 Fix syntax highlighting and rendering issues.
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/utils/highlight.test.ts
  packages/cli/src/ui/utils/highlight.ts
Labels: kind/enhancement, priority/p2, area/ux

#6240 feat(core): Save large tool outputs to a file and return truncated lines
  packages/a2a-server/src/utils/testing_utils.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/ui/components/messages/ToolGroupMessage.tsx
  packages/cli/src/ui/hooks/useReactToolScheduler.ts
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/cli/src/ui/types.ts
  packages/core/src/config/config.ts
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/coreToolScheduler.ts
  packages/core/src/core/nonInteractiveToolExecutor.test.ts
  packages/core/src/core/turn.ts
  packages/core/src/tools/read-file.test.ts
  packages/core/src/tools/read-file.ts
Labels: status/need-issue

#7832 Fix(core): Fix stream validation logic
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7749 fix(ci): fix windows e2e tests
  .github/workflows/e2e.yml
  integration-tests/shell-service.test.ts
  integration-tests/test-helper.ts
  package.json
Labels: status/need-issue, maintainer:e2e:ok

#7267 Fix issues where escape codes could end up on startup in the input prompt
  packages/cli/src/gemini.test.tsx
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/contexts/KeypressContext.tsx
  packages/cli/src/ui/hooks/useKeypress.test.ts
  packages/cli/src/ui/utils/kittyProtocolDetector.ts
Labels: kind/bug, priority/p1, area/ux

#5834 prevent auto-execute on paste and preserve multi-line content in chat input
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: kind/bug, good first issue, priority/p2, area/ux

#7824 fix: handle vpc-sc violations in LoadCodeAssist method
  packages/core/src/code_assist/server.test.ts
  packages/core/src/code_assist/server.ts
  packages/core/src/code_assist/types.ts
Labels: status/need-issue

#6080 feat(ui): improve discoverability of MCP slash commands
  packages/cli/src/ui/components/Help.tsx
  packages/cli/src/ui/components/SuggestionsDisplay.tsx
  packages/cli/src/ui/hooks/useSlashCompletion.test.ts
  packages/cli/src/ui/hooks/useSlashCompletion.ts
Labels: kind/enhancement, priority/p3, sub-area/mcp

#5488 feat(ui): Introduce useUI Hook and UIContext
  docs/mermaid/context.mmd
  docs/mermaid/render-path.mmd
  package-lock.json
  packages/cli/src/core/auth.ts
  packages/cli/src/core/initializer.ts
  packages/cli/src/core/theme.ts
  packages/cli/src/gemini.test.tsx
  packages/cli/src/gemini.tsx
  packages/cli/src/services/BuiltinCommandLoader.test.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/AppContainer.test.tsx
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/commands/ideCommand.test.ts
  packages/cli/src/ui/components/AppHeader.tsx
  packages/cli/src/ui/components/Composer.test.tsx
  packages/cli/src/ui/components/Composer.tsx
  packages/cli/src/ui/components/DialogManager.tsx
  packages/cli/src/ui/components/Footer.test.tsx
  packages/cli/src/ui/components/Footer.tsx
  packages/cli/src/ui/components/HistoryItemDisplay.tsx
  packages/cli/src/ui/components/MainContent.tsx
  packages/cli/src/ui/components/Notifications.tsx
  packages/cli/src/ui/components/QuittingDisplay.tsx
  packages/cli/src/ui/components/messages/ToolGroupMessage.test.tsx
  packages/cli/src/ui/components/messages/ToolGroupMessage.tsx
  packages/cli/src/ui/contexts/AppContext.tsx
  packages/cli/src/ui/contexts/ConfigContext.tsx
  packages/cli/src/ui/contexts/UIActionsContext.tsx
  packages/cli/src/ui/contexts/UIStateContext.tsx
  packages/cli/src/ui/hooks/atCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useFolderTrust.test.ts
  packages/cli/src/ui/hooks/useFolderTrust.ts
  packages/cli/src/ui/hooks/useReactToolScheduler.ts
  packages/cli/src/ui/hooks/useThemeCommand.ts
  packages/cli/src/ui/types.ts
  packages/core/index.ts
  packages/core/package.json
Labels: kind/bug, priority/p2, sub-area/installation, area/platform

#7859 Fix(core): Do not retry if last chunk is empty with finishReason previous chunks are good
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7879 Fix ctrl-c/esc while Authenticating.
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/components/DialogManager.tsx
Labels: kind/bug, priority/p2, sub-area/installation, area/platform

#7902 chore(release): v0.3.4
  package-lock.json
  package.json
  packages/a2a-server/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/test-utils/package.json
  packages/vscode-ide-companion/package.json
Labels: status/need-issue

#7935 fix(ui): disable input prompt during tool confirmation
  packages/cli/src/ui/AppContainer.tsx
Labels: kind/bug, priority/p0, area/ux

#8007 fix(ide): fix crash on windows when null command is returned
  packages/core/src/ide/process-utils.ts
Labels: kind/bug, priority/p0, sub-area/ide

#7394 fix: hide tips when folder trust dialog is open
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/components/AppHeader.tsx
  packages/cli/src/ui/hooks/useFolderTrust.test.ts
  packages/cli/src/ui/hooks/useFolderTrust.ts
Labels: status/need-issue

#7815 Remove org/repo install support
  packages/cli/src/commands/extensions/install.test.ts
  packages/cli/src/commands/extensions/install.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7952 refactor(core): Introduce LlmUtilityService and promptIdContext
  packages/cli/src/nonInteractiveCli.ts
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/config/config.test.ts
  packages/core/src/config/config.ts
  packages/core/src/core/baseLlmClient.test.ts
  packages/core/src/core/baseLlmClient.ts
  packages/core/src/index.ts
  packages/core/src/tools/smart-edit.test.ts
  packages/core/src/tools/smart-edit.ts
  packages/core/src/utils/llm-edit-fixer.test.ts
  packages/core/src/utils/llm-edit-fixer.ts
  packages/core/src/utils/promptIdContext.ts
Labels: priority/p3, area/core, kind/cleanup, status/bot-triaged

#8057 Add clearcut logging for extensions install command
  packages/cli/src/commands/extensions/install.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/core/index.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts
  packages/core/src/telemetry/types.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#8037 refactor(ide): extract IDE context types into a separate file
  packages/core/src/core/client.ts
  packages/core/src/ide/ide-client.ts
  packages/core/src/ide/ideContext.test.ts
  packages/core/src/ide/ideContext.ts
  packages/core/src/ide/types.ts
  packages/core/src/index.ts
Labels: kind/enhancement, area/extensibility

#8039 feat(core): Only summarize long tool output for shell command
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/core/src/config/config.ts
  packages/core/src/core/coreToolScheduler.ts
Labels: status/need-issue

#8103 Limit recursion when looking for .gitignore files
  packages/core/src/utils/gitIgnoreParser.ts
Labels: kind/bug, area/performance, status/bot-triaged

#8107 feat(ide): Update context filtering to be done CLI-side + update port discovery logic
  packages/core/src/ide/constants.ts
  packages/core/src/ide/ide-client.test.ts
  packages/core/src/ide/ide-client.ts
  packages/core/src/ide/ideContext.test.ts
  packages/core/src/ide/ideContext.ts
Labels: kind/enhancement, area/extensibility

#8110 [Part 1/6] feat(telemetry): add rate limiter and high-water mark tracker with tests
  packages/core/src/telemetry/high-water-mark-tracker.test.ts
  packages/core/src/telemetry/high-water-mark-tracker.ts
  packages/core/src/telemetry/index.ts
  packages/core/src/telemetry/rate-limiter.test.ts
  packages/core/src/telemetry/rate-limiter.ts
Labels: kind/enhancement, priority/p2, sub-area/performance, sub-area/memory

#8152 Release Process vNext
  .github/actions/publish-release/action.yml
  .github/workflows/nightly-release.yml
  .github/workflows/promote-release.yml
  .github/workflows/release.yml
  .yamllint.yml
  eslint.config.js
  package-lock.json
  package.json
  packages/a2a-server/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/test-utils/package.json
  packages/vscode-ide-companion/package.json
  scripts/get-release-version.js
  scripts/tests/get-release-version.test.js
Labels: kind/duplicate, sub-area/testing, kind/parent-issue, area/contribution, maintainer

#8100 Extensions update command
  packages/cli/src/ui/commands/extensionsCommand.test.ts
  packages/cli/src/ui/commands/extensionsCommand.ts
Labels: kind/enhancement, priority/p2, area/extensibility

#8086 Add .geminiignore support to the glob tool.
  packages/core/src/services/fileDiscoveryService.ts
  packages/core/src/tools/glob.test.ts
  packages/core/src/tools/glob.ts
  packages/core/src/tools/ls.test.ts
  packages/core/src/tools/ls.ts
  packages/core/src/tools/read-many-files.ts
Labels: kind/bug, priority/p2, area/core

#7464 Fix: connect on docker devcontainer to vscode-ide
  packages/cli/src/utils/sandbox.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: kind/bug, area/extensibility

#8362 fix(ui): Correct footer measurement and prevent negative terminal height
  packages/cli/src/ui/AppContainer.test.tsx
  packages/cli/src/ui/AppContainer.tsx
Labels: kind/bug, priority/p0, area/ux

#8139 feat: Add /chat share command
  docs/cli/commands.md
  packages/cli/src/ui/commands/chatCommand.test.ts
  packages/cli/src/ui/commands/chatCommand.ts
Labels: kind/enhancement, good first issue, priority/p3, area/ux, status/possible-duplicate, status/bot-triaged

#8154 Fix #8077: Settings command overwrites entire JSON file, leaking environment variables
  npm-shrinkwrap.json
  packages/cli/package.json
  packages/cli/src/config/settings.ts
  packages/cli/src/ui/components/SettingsDialog.test.tsx
  packages/cli/src/ui/components/ThemeDialog.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/utils/commentJson.test.ts
  packages/cli/src/utils/commentJson.ts
Labels: kind/bug, priority/p0, area/core, area/security-privacy, status/bot-triaged

#8427 refactor(core): Use BaseLlmClient for LLM-based loop detection
  packages/core/src/services/loopDetectionService.test.ts
  packages/core/src/services/loopDetectionService.ts
Labels: area/core, kind/cleanup, status/bot-triaged

#6665 feat: auto-approve pending tool calls when auto_edit/yolo is activated
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/hooks/useAutoAcceptIndicator.test.ts
  packages/cli/src/ui/hooks/useAutoAcceptIndicator.ts
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
Labels: status/need-issue, maintainer:e2e:ok

#8424 refactor(core): Migrate next speaker check to use BaseLlmClient
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/utils/nextSpeakerChecker.test.ts
  packages/core/src/utils/nextSpeakerChecker.ts
Labels: area/core, kind/cleanup, status/bot-triaged

#8355 feat(extensions) - Add local/remote for mcp servers
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
Labels: kind/enhancement, area/extensibility, area/security-privacy

#8391 fix(tests): Cleans up setup test and fix behavior test
  packages/core/src/core/client.test.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#5539 feat (cli): Add command search using Ctrl+r
  packages/cli/src/config/keyBindings.ts
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/components/PrepareLabel.test.tsx
  packages/cli/src/ui/components/PrepareLabel.tsx
  packages/cli/src/ui/components/SuggestionsDisplay.tsx
  packages/cli/src/ui/components/__snapshots__/InputPrompt.test.tsx.snap
  packages/cli/src/ui/components/__snapshots__/PrepareLabel.test.tsx.snap
  packages/cli/src/ui/hooks/useReverseSearchCompletion.tsx
  packages/cli/src/ui/keyMatchers.test.ts
Labels: kind/enhancement, priority/p2, area/ux

#8010 feat(security) - Use hybrid token storage when flag is enabled
  packages/core/src/mcp/oauth-token-storage.test.ts
  packages/core/src/mcp/oauth-token-storage.ts
  packages/core/src/mcp/token-storage/index.ts
Labels: status/need-issue

#8489 update shell info
  packages/core/src/tools/__snapshots__/shell.test.ts.snap
  packages/core/src/tools/shell.ts
Labels: status/need-issue

#8506 Fix references to old name of npm-shrinkwrap.json.
  .github/CODEOWNERS
  .github/actions/publish-release/action.yml
  .github/workflows/release.yml
Labels: status/need-issue

#8479 docs(ide): define diffing interface for companion extension spec
  docs/ide-companion-spec.md
Labels: kind/enhancement, area/extensibility

#8491 feat(vscode-ide-companion): add auth token validation to IDE server
  docs/ide-companion-spec.md
  packages/vscode-ide-companion/src/ide-server.test.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: status/need-issue

#8430 Fix mixed input crash by adding proper error handling 8304
  integration-tests/mixed-input-crash.test.ts
  packages/cli/src/gemini.test.tsx
  packages/cli/src/gemini.tsx
Labels: kind/bug, area/core, status/bot-triaged

#8356 Improve theme name color and readability in ThemeDialog
  packages/cli/src/ui/themes/ayu.ts
  packages/cli/src/ui/themes/dracula.ts
  packages/cli/src/ui/themes/github-dark.ts
Labels: kind/bug, priority/p1, area/ux, maintainer

#8490 feat(ide): add auth token support to IdeClient
  packages/core/src/ide/ide-client.test.ts
  packages/core/src/ide/ide-client.ts
Labels: status/need-issue

#7698 Fix(triage): Update pr-triage.sh script
  .github/scripts/pr-triage.sh
Labels: status/need-issue

#8443 refactor(core): Use BaseLlmClient for utility LLM calls in edit corrector
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/write-file.test.ts
  packages/core/src/tools/write-file.ts
  packages/core/src/utils/editCorrector.test.ts
  packages/core/src/utils/editCorrector.ts
Labels: area/core, kind/cleanup, status/need-issue, status/bot-triaged

#8520 choose subagent model via env var
  packages/core/src/tools/base-subagent-tool.ts
Labels: status/need-issue

#8526 Ammend subagents prompts to use web fetcher
  packages/core/src/tools/codebase-investigator.ts
  packages/core/src/tools/planner.ts
Labels: status/need-issue

#8371 cleanup(extension) - Add tests for the install command
  packages/cli/src/commands/extensions/install.test.ts
Labels: kind/enhancement, priority/p2, status/need-issue, area/extensibility, status/bot-triaged

#8562 chore(settings): enable setting migration
  packages/cli/src/config/settings.ts
Labels: status/need-issue

#8510 refactor: Replace exec with spawn
  packages/cli/src/ui/hooks/useGitBranchName.test.ts
  packages/cli/src/ui/hooks/useGitBranchName.ts
  packages/cli/src/ui/utils/clipboardUtils.ts
  packages/core/src/ide/ide-installer.test.ts
  packages/core/src/ide/ide-installer.ts
  packages/core/src/services/gitService.test.ts
  packages/core/src/services/gitService.ts
  packages/core/src/utils/editor.test.ts
  packages/core/src/utils/editor.ts
  packages/core/src/utils/shell-utils.ts
  scripts/telemetry_utils.js
Labels: status/need-issue

#8497 Remove unused code.
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
Labels: kind/bug, priority/p1, status/need-issue

#8518 feat(telemetry): Add telemetry and metrics for model routing
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/nonInteractiveToolExecutor.test.ts
  packages/core/src/routing/modelRouterService.test.ts
  packages/core/src/routing/modelRouterService.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.test.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts
  packages/core/src/telemetry/constants.ts
  packages/core/src/telemetry/loggers.test.ts
  packages/core/src/telemetry/loggers.ts
  packages/core/src/telemetry/metrics.test.ts
  packages/core/src/telemetry/metrics.ts
  packages/core/src/telemetry/types.ts
Labels: status/need-issue

#8585 feat: Add `-o` as alias for `--output-format`
  packages/cli/src/config/config.ts
Labels: status/need-issue

#8593 Move headless.md to docs folder
  docs/cli/authentication.md
  docs/cli/index.md
  docs/headless.md
Labels: status/need-issue

#8601 fix(tests): look for json in thrown error
  integration-tests/json-output.test.ts
Labels: status/need-issue

#8624 chore: update erroneous model version added by external contrib
  packages/cli/src/utils/commentJson.test.ts
Labels: status/need-issue

#8395 fix(tests): improve test reliability and performance
  packages/core/src/utils/fileUtils.test.ts
  packages/core/src/utils/memoryDiscovery.test.ts
Labels: kind/flake, status/need-issue, maintainer:e2e:ok

#8599 Fix automatic compression bug
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
Labels: status/need-issue

#8645 chore(release): bump version to 0.7.0-nightly.20250917.0b10ba2c
  npm-shrinkwrap.json
  package.json
  packages/a2a-server/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/test-utils/package.json
  packages/vscode-ide-companion/package.json
Labels: status/need-issue

#8498 Add simple extensions release flow support
  docs/extension-releasing.md
  packages/cli/src/commands/extensions/install.ts
  packages/cli/src/commands/extensions/link.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/extensions/github.test.ts
  packages/cli/src/config/extensions/github.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-issue, status/need-retesting

#6919 fix(mcp): Display OAuth authentication messages in CLI UI instead of debug console
  packages/cli/src/ui/commands/mcpCommand.test.ts
  packages/cli/src/ui/commands/mcpCommand.ts
  packages/cli/src/utils/events.ts
  packages/core/src/mcp/oauth-provider.ts
Labels: kind/bug, priority/p2, area/ux, status/need-issue, maintainer:e2e:ok

#8239 refactor(ui): Optimize rendering performance
  package.json
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/components/Composer.tsx
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/components/shared/text-buffer.ts
  packages/cli/src/ui/contexts/FocusContext.tsx
  packages/cli/src/ui/contexts/SessionContext.test.tsx
  packages/cli/src/ui/contexts/SessionContext.tsx
  packages/cli/src/ui/contexts/UIStateContext.tsx
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/cli/src/ui/hooks/useStateAndRef.ts
Labels: kind/bug, priority/p0, area/ux, status/need-issue

#8111 [Part 2/6] feat(telemetry): add activity detector with user interaction tracking
  packages/core/src/telemetry/activity-detector.test.ts
  packages/core/src/telemetry/activity-detector.ts
  packages/core/src/telemetry/activity-types.ts
  packages/core/src/telemetry/index.ts
Labels: kind/enhancement, priority/p2, sub-area/performance, sub-area/memory, status/need-issue, maintainer:e2e:ok

#8652 permissiong for nightly job
  .github/actions/create-pull-request/action.yml
  .github/workflows/create-patch-pr.yml
  .github/workflows/nightly-release.yml
  .github/workflows/promote-release.yml
Labels: status/need-issue

#8669 Mk fix nightly
  .github/actions/create-pull-request/action.yml
Labels: status/need-issue

#8512 feat(vscode-ide-companion): harden ide-server with CORS and host validation
  packages/vscode-ide-companion/src/ide-server.test.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: status/need-issue

#8588 feat(CI): Package docker containers to GHCR for PRs.
  .github/actions/push-docker/action.yml
  .github/workflows/ci.yml
Labels: status/need-issue

#8676 fixing error
  packages/cli/src/config/config.test.ts
Labels: status/need-issue

#8691 Improve compression splitpoint logic.
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
Labels: status/need-issue

#8736 Better parsing of github extension source uris
  packages/cli/src/config/extensions/github.test.ts
  packages/cli/src/config/extensions/github.ts
Labels: status/need-issue

#8647 refactor(shell): Send AnsiOutput when ShowColor is false
  packages/cli/src/ui/components/messages/ToolMessage.tsx
  packages/cli/src/ui/hooks/shellCommandProcessor.ts
  packages/core/src/services/shellExecutionService.test.ts
  packages/core/src/services/shellExecutionService.ts
Labels: status/need-issue

#8750 fix(release): correctly parse channel argument in patch workflow
  .github/workflows/release-patch-from-comment.yml
Labels: status/need-issue

#8348 feat(cli): configure policy engine from existing settings
  packages/cli/src/config/config.ts
  packages/cli/src/config/policy-engine.integration.test.ts
  packages/cli/src/config/policy.test.ts
  packages/cli/src/config/policy.ts
  packages/core/src/index.ts
  packages/core/src/policy/policy-engine.test.ts
  packages/core/src/policy/policy-engine.ts
Labels: kind/enhancement, priority/p2, area/tools, status/need-issue

#8511 Add support for auto-updating git extensions
  packages/cli/src/commands/extensions/install.test.ts
  packages/cli/src/commands/extensions/install.ts
  packages/cli/src/commands/extensions/update.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/extensions/github.test.ts
  packages/cli/src/config/extensions/github.ts
  packages/cli/src/config/extensions/update.test.ts
  packages/cli/src/config/extensions/update.ts
  packages/cli/src/test-utils/createExtension.ts
  packages/cli/src/test-utils/mockCommandContext.ts
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/commands/extensionsCommand.test.ts
  packages/cli/src/ui/commands/extensionsCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useExtensionUpdates.test.ts
  packages/cli/src/ui/hooks/useExtensionUpdates.ts
  packages/cli/src/ui/state/extensions.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement, status/need-issue, area/extensibility

#7829 add(mcp): Add MCP Server name to ToolCallEvent OTel logging
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts
  packages/core/src/telemetry/loggers.test.ts
  packages/core/src/telemetry/types.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-issue, status/need-retesting, maintainer:e2e:ok

#8767 patch e2e vnext
  .github/workflows/release-patch-1-create-pr.yml
  .github/workflows/release-patch-2-trigger.yml
  .github/workflows/release-patch-3-release.yml
  .github/workflows/release-patch-from-comment.yml
  scripts/releasing/create-patch-pr.js
  scripts/releasing/patch-comment.js
  scripts/releasing/patch-create-comment.js
  scripts/releasing/patch-trigger.js
Labels: status/need-issue

#8787 more patching
  .github/actions/publish-release/action.yml
  .github/workflows/e2e.yml
  .github/workflows/release-patch-1-create-pr.yml
  .gitignore
Labels: status/need-issue

#8810 ci fixes
  .github/workflows/ci.yml
Labels: status/need-issue

#8811 Prompte telemetry, debug and proxy flags to global
  packages/cli/src/config/config.ts
Labels: maintainer:e2e:ok

#8685 fix(cli): ctrl c/ctrl d close cli when in dialogs
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/AppContainer.test.tsx
  packages/cli/src/ui/AppContainer.tsx
Labels: status/need-issue, maintainer:e2e:ok

#8898 Reset 2
  .github/workflows/release-patch-1-create-pr.yml
  scripts/releasing/create-patch-pr.js
Labels: status/need-issue

#8906 Finalizing Patching End 2 End
  .github/workflows/release-patch-2-trigger.yml
  docs/releases.md
  scripts/releasing/patch-trigger.js
Labels: status/need-issue

#8797 Fix extensions enablement bugs
  docs/extension.md
  packages/cli/src/commands/extensions/disable.ts
  packages/cli/src/commands/extensions/enable.ts
  packages/cli/src/config/extensions/extensionEnablement.test.ts
  packages/cli/src/config/extensions/extensionEnablement.ts
Labels: status/need-issue

#8746 for github release extensions, dont require built assets
  packages/cli/src/config/extensions/github.ts
Labels: status/need-issue

#8923 Revert "feat(third_party) Port `get-ripgrep`."
  .gitignore
  esbuild.config.js
  npm-shrinkwrap.json
  package.json
  packages/core/package.json
  packages/core/src/tools/ripGrep.test.ts
  packages/core/src/tools/ripGrep.ts
  packages/core/tsconfig.json
  scripts/build_package.js
  scripts/clean.js
  third_party/get-ripgrep/package.json
  third_party/get-ripgrep/src/downloadRipGrep.js
  third_party/get-ripgrep/src/downloadRipGrep.test.ts
  third_party/get-ripgrep/src/index.js
  third_party/get-ripgrep/src/index.ts
  third_party/get-ripgrep/tsconfig.json
Labels: status/need-issue

#8927 Update extension-releasing.md to have more info
  docs/extension-releasing.md
Labels: status/need-issue

#8934 fix(security): Pin wrap-ansi to 9.0.2
  package-lock.json
  package.json
  packages/cli/package.json
Labels: status/need-issue

#8403 docs: Fix broken Extension example
  docs/extension.md
Labels: kind/enhancement, priority/p1, area/models, status/need-issue, status/need-retesting, maintainer:e2e:ok

#8693 Support rendering function calls and responses when sharing chat to markdown
  packages/cli/src/ui/commands/chatCommand.test.ts
  packages/cli/src/ui/commands/chatCommand.ts
Labels: status/need-issue, maintainer:e2e:ok

#8386 Correctly support comma-separated values for `--allowed-tools`
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-issue, status/need-retesting

#8946 fix(cli): Revert the code to hide tips when showing trust dialog
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/components/AppHeader.tsx
  packages/cli/src/ui/hooks/useFolderTrust.test.ts
  packages/cli/src/ui/hooks/useFolderTrust.ts
Labels: status/need-issue

#8730 fix(#7777): screen reader accessibility setting not working
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#8809 Filter out the 'trust' attribute from extension MCP server configs
  docs/extension.md
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
Labels: status/need-issue

#8380 feat(dev): add pre-commit hook for formatting and linting
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: status/need-issue, maintainer:e2e:ok

#8761 (feat): Add a ToDo tool to track ongoing task lists
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/gemini.test.tsx
  packages/core/src/config/config.ts
  packages/core/src/index.ts
  packages/core/src/tools/write-todos.test.ts
  packages/core/src/tools/write-todos.ts
Labels: area/models, status/need-issue

#7800 fix(mcp): handle `gemini mcp add` scope correctly in home directory
  packages/cli/src/commands/mcp/add.test.ts
  packages/cli/src/commands/mcp/add.ts
Labels: kind/bug, priority/p1, area/tools, status/need-issue, maintainer:e2e:ok

#8765 Fix bug where users are unable to re-enter disconnected terminals.
  packages/cli/src/test-utils/render.tsx
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/components/Composer.tsx
  packages/cli/src/ui/components/HistoryItemDisplay.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/components/MainContent.tsx
  packages/cli/src/ui/components/__snapshots__/InputPrompt.test.tsx.snap
  packages/cli/src/ui/components/messages/ToolGroupMessage.tsx
  packages/cli/src/ui/components/messages/ToolMessage.tsx
  packages/cli/src/ui/contexts/KeypressContext.tsx
  packages/cli/src/ui/contexts/ShellFocusContext.tsx
  packages/cli/src/ui/contexts/UIStateContext.tsx
  packages/cli/src/ui/hooks/useFocus.test.ts
  packages/cli/src/ui/hooks/useFocus.ts
Labels: status/need-issue

#9007 fix(cli): support comma separated values for extensions and allowed mcp server names
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#8760 feat(ide): Read IDE info from discovery file
  docs/ide-companion-spec.md
  packages/core/src/ide/detect-ide.test.ts
  packages/core/src/ide/detect-ide.ts
  packages/core/src/ide/ide-client.test.ts
  packages/core/src/ide/ide-client.ts
Labels: status/need-issue

#9122 Store installed release version as a part of install metadata
  packages/cli/src/config/extension.ts
  packages/cli/src/config/extensions/github.ts
  packages/core/src/config/config.ts
Labels: status/need-issue

#8339 Telemtry(extensions) - Add logging for extension events
  docs/telemetry.md
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/extensions/update.test.ts
  packages/cli/src/ui/hooks/useExtensionUpdates.test.ts
  packages/core/index.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/index.ts
Labels: status/need-issue, area/extensibility

#9113 feat(config): Support telemetry configuration via environment variables
  docs/cli/configuration.md
  docs/telemetry.md
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/core/src/telemetry/config.test.ts
  packages/core/src/telemetry/config.ts
  packages/core/src/telemetry/index.ts
Labels: status/need-issue

#8792 feat(cli): Add permissions command to modify trust settings
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/extensions/update.test.ts
  packages/cli/src/config/settings.test.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/trustedFolders.test.ts
  packages/cli/src/config/trustedFolders.ts
  packages/cli/src/services/BuiltinCommandLoader.test.ts
  packages/cli/src/services/BuiltinCommandLoader.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/AppContainer.tsx
  packages/cli/src/ui/commands/permissionsCommand.test.ts
  packages/cli/src/ui/commands/permissionsCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/components/DialogManager.tsx
  packages/cli/src/ui/components/PermissionsModifyTrustDialog.test.tsx
  packages/cli/src/ui/components/PermissionsModifyTrustDialog.tsx
  packages/cli/src/ui/contexts/UIActionsContext.tsx
  packages/cli/src/ui/contexts/UIStateContext.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useExtensionUpdates.test.ts
  packages/cli/src/ui/hooks/useFolderTrust.test.ts
  packages/cli/src/ui/hooks/useFolderTrust.ts
  packages/cli/src/ui/hooks/usePermissionsModifyTrust.test.ts
  packages/cli/src/ui/hooks/usePermissionsModifyTrust.ts
Labels: status/need-issue

#8938 feat: add message bus integration for tool confirmation
  packages/cli/src/config/config.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/core/src/config/config.ts
  packages/core/src/tools/message-bus-integration.test.ts
  packages/core/src/tools/tools.ts
Labels: status/need-issue

#8737 Update Paid tier specific privacy notice.
  packages/cli/src/ui/privacy/CloudFreePrivacyNotice.tsx
Labels: status/need-issue

#9147 use github release artifacts instead of cloning repos when available
  packages/cli/src/config/extensions/github.ts
Labels: status/need-issue

#8929 feat(ci): Add a "verify release" action + workflow to the pipeline
  .github/actions/publish-release/action.yml
  .github/actions/tag-npm-release/action.yml
  .github/actions/verify-release/action.yml
  .github/workflows/release-change-tags.yml
  .github/workflows/release-manual.yml
  .github/workflows/verify-release.yml
Labels: status/need-issue

#9150 Fix(quality): Refine Stream Validation Logic
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
Labels: status/need-issue

#9156 Fix: Only log message bus debug info when feature is enabled
  packages/core/src/config/config.ts
Labels: status/need-issue

#9121 Improve extensions consent flow, command formatting, github-release behavior
  packages/cli/src/commands/extensions/install.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/extensions/github.ts
Labels: status/need-issue

#8954 handling propper checkouts for releasemanual
  .github/workflows/release-manual.yml
Labels: status/need-issue

#8964 Releasing: Version mgmt
  package-lock.json
  package.json
  scripts/get-release-version.js
  scripts/releasing/create-patch-pr.js
  scripts/tests/get-release-version.test.js
Labels: status/need-issue

#9249 change patch name for consistency
  .github/workflows/release-patch-0-from-comment.yml
Labels: status/need-issue

#9177 Add integration test for extensions
  integration-tests/extensions-install.test.ts
  integration-tests/test-helper.ts
Labels: status/need-issue
