Repository google-gemini/gemini-cli, pull requests merged in 2025-10, with the labels that each got.

#5952 fix(cli): honor argv @path in interactive sessions (quoted + unquoted)
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/gemini.test.tsx
Labels: kind/bug, priority/p1, area/core, status/need-issue, maintainer:e2e:ok

#9497 fix(integration): Added shell specification for winpty
  integration-tests/ctrl-c-exit.test.ts
  integration-tests/test-helper.ts
Labels: maintainer:e2e:ok

#10289 Re-submission: Make --allowed-tools work in non-interactive mode
  integration-tests/run_shell_command.test.ts
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/nonInteractiveCli.test.ts
  packages/core/src/tools/shell.test.ts
  packages/core/src/tools/shell.ts
  packages/core/src/utils/shell-utils.ts
  packages/core/src/utils/tool-utils.test.ts
  packages/core/src/utils/tool-utils.ts
Labels: maintainer:e2e:ok

#7662 feat(sessions): Add automatic session cleanup and retention policy
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/components/__snapshots__/SettingsDialog.test.tsx.snap
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/cli/src/utils/sessionCleanup.integration.test.ts
  packages/cli/src/utils/sessionCleanup.test.ts
  packages/cli/src/utils/sessionCleanup.ts
  packages/cli/src/utils/sessionUtils.ts
  packages/core/src/core/client.ts
  packages/core/src/core/geminiChat.ts
  packages/core/src/services/chatRecordingService.ts
Labels: status/need-issue

#8122 [Part 4/6] feat(telemetry): add memory monitor with activity-aware recording and tests
  packages/core/src/telemetry/index.ts
  packages/core/src/telemetry/memory-monitor.test.ts
  packages/core/src/telemetry/memory-monitor.ts
  packages/core/src/utils/formatters.test.ts
  packages/core/src/utils/formatters.ts
Labels: kind/enhancement, priority/p2, sub-area/performance, sub-area/memory, status/need-issue
