Repository google-gemini/gemini-cli, pull requests merged in 2025-06, with the labels that each got.

#1514 Remove GEMINI_CODE_ASSIST env variable from configuration.md doc
  docs/cli/configuration.md
Labels: documentation

#1557 fix(telemetry): handle all promise rejections in ClearcutLogger
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
Labels: bug

#1480 Fix typos and formatting issues
  GEMINI.md
  scripts/build.js
Labels: kind/documentation
