Repository google-gemini/gemini-cli, pull requests merged in 2025-07, with the labels that each got.

#1955 feat: Add markdown table rendering support
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.tsx
  packages/cli/src/ui/utils/TableRenderer.tsx
Labels: kind/enhancement

#3062 feat(workflows): add automated and scheduled PR triage
  .github/pull_request_template.md
  .github/workflows/gemini-automated-pr-triage.yml
  .github/workflows/gemini-scheduled-pr-triage.yml
Labels: kind/enhancement, priority/p2, area/testing

#2781 fix: remove unnecessary whitespace
  docs/troubleshooting.md
Labels: kind/bug, area/auth, priority/p1

#2118 fix(client): get model from config in flashFallbackHandler
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
Labels: kind/bug, priority/p0, priority/p1, area/core, area/models

#3147 Fixed Google User Id pass to Clearcut
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/utils/user_id.test.ts
  packages/core/src/utils/user_id.ts
Labels: kind/bug, kind/enhancement, good first issue, area/auth, priority/p2, area/ux

#3128 Add and improve JSDoc comments for core tool methods
  CONTRIBUTING.md
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/core/src/tools/glob.ts
  packages/core/src/tools/mcp-client.ts
  packages/core/src/tools/shell.ts
  packages/core/src/tools/web-search.ts
  packages/core/src/tools/write-file.ts
Labels: kind/bug, kind/enhancement, area/auth, priority/p1, area/ux

#2652 Refactor text-buffer to use reducer
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/components/shared/text-buffer.ts
Labels: status/need-issue

#2852 Releasing: Utilizing Github Actions and Tagging for release.
  .gcp/release-docker.yaml
  .github/workflows/release.yml
  .github/workflows/scheduled-nightly-release.yml
  docs/index.md
  docs/npm.md
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package-lock.json
  packages/core/package.json
  scripts/bind_package_dependencies.js
  scripts/bind_package_version.js
  scripts/build_sandbox.js
  scripts/check-versions.js
  scripts/clean.js
  scripts/prepare-core-package.js
  scripts/prepare-package.js
  scripts/prepublish.js
  scripts/publish-sandbox.js
  scripts/version.js
Labels: status/need-issue

#3167 ci: update issue templates to use GitHub alert
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: status/need-issue

#3206 Mk nightly relase tag formatting
  .gcp/release-docker.yaml
  .github/workflows/release.yml
  package.json
Labels: status/need-issue

#3264 Mk sign nightly release commits
  .gcp/release-docker.yaml
  .github/workflows/scheduled-nightly-release.yml
Labels: status/need-issue

#2862 fix a command usage issue in deployment.md
  docs/deployment.md
Labels: status/need-issue

#3247 Doc: update gemini-cli README.md to require Node.js version 20+
  README.md
Labels: kind/bug, area/windows, priority/p1, area/installation

#3284 fix typos in diverse files
  GEMINI.md
  docs/cli/configuration.md
  docs/npm.md
  docs/quota-and-pricing.md
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/components/messages/CompressionMessage.tsx
  packages/cli/src/ui/components/messages/ToolMessage.test.tsx
  packages/cli/src/ui/components/shared/MaxSizedBox.test.tsx
  packages/cli/src/ui/components/shared/MaxSizedBox.tsx
  packages/core/src/utils/editCorrector.ts
  packages/core/src/utils/editor.ts
  packages/core/src/utils/nextSpeakerChecker.ts
  scripts/start.js
Labels: status/need-issue

#3333 fix(cli): Group cancelled tool call responses to prevent API errors
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
Labels: kind/bug, area/windows, priority/p0

#3321 Relase: Clean up and condensing
  .gcp/publish-dry-run.yaml
  .gcp/release.yaml
  .github/workflows/release.yml
  .github/workflows/scheduled-nightly-release.yml
  docs/npm.md
  integration-tests/list_directory.test.js
  package-lock.json
  package.json
  scripts/get-release-version.js
  scripts/tag-release.js
  scripts/tests/get-release-version.test.js
  scripts/tests/test-setup.ts
  scripts/tests/vitest.config.ts
Labels: status/need-issue

#3335 cleaning up prompts for release
  .github/workflows/release.yml
Labels: status/need-issue

#3300 fix(core): Sanitize tool parameters to fix 400 API errors
  package-lock.json
  package.json
  packages/cli/src/ui/hooks/useLoadingIndicator.test.ts
  packages/core/package.json
  packages/core/src/tools/mcp-client.test.ts
  packages/core/src/tools/mcp-client.ts
  packages/core/src/tools/tool-registry.test.ts
  packages/core/src/tools/tool-registry.ts
Labels: status/need-issue

#2932 Fix #2922: Prevent @ concatenation to valid paths in shellmode.
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/components/shared/text-buffer.ts
Labels: kind/bug, priority/p2, status/in-review, area/ux, status/need-issue

#2883 feat: Handle inline content modification in tool scheduler
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/coreToolScheduler.ts
  packages/core/src/tools/tools.ts
Labels: status/need-issue

#3339 Update @google/genai -> 1.8.0
  package-lock.json
  packages/core/package.json
Labels: kind/enhancement, priority/p3, area/i18n

#3056 feat: add user startup warnings, add home directory check
  packages/cli/src/gemini.tsx
  packages/cli/src/utils/userStartupWarnings.test.ts
  packages/cli/src/utils/userStartupWarnings.ts
Labels: kind/bug, kind/enhancement, priority/p1

#3418 Release misc
  .github/workflows/release.yml
  .vscode/launch.json
  integration-tests/list_directory.test.js
  integration-tests/run-tests.js
  integration-tests/test-helper.js
  package.json
Labels: status/need-issue

#3349 feat(core): improve error messages in isCommandAllowed
  packages/core/src/tools/shell.test.ts
  packages/core/src/tools/shell.ts
Labels: kind/bug, kind/enhancement, priority/p2, area/core

#3416 fix: respect env variables in .env for settings.json variable substitution
  packages/cli/src/config/auth.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/settings.ts
Labels: kind/bug, kind/enhancement, area/GCA, priority/p2

#3362 Fix nested markdown Rendering for table headers and rows #3331
  packages/cli/src/ui/utils/InlineMarkdownRenderer.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.tsx
  packages/cli/src/ui/utils/TableRenderer.tsx
Labels: status/need-issue

#3387 @file don't respect config respectGitIgnore=false (#3382)
  packages/cli/src/ui/hooks/atCommandProcessor.test.ts
  packages/cli/src/ui/hooks/atCommandProcessor.ts
  packages/cli/src/ui/hooks/useCompletion.integration.test.ts
  packages/cli/src/ui/hooks/useCompletion.ts
  packages/core/src/services/fileDiscoveryService.ts
Labels: status/need-issue

#3360 Re-enable backticks in shell tool usage.
  packages/core/src/tools/shell.test.ts
  packages/core/src/tools/shell.ts
Labels: kind/bug, kind/enhancement, priority/p3, area/quality

#3464 Add --allowed_mcp_server_names flag
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#3043 fix: EditTool can clobber human edits to the same file.
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/write-file.test.ts
  packages/core/src/tools/write-file.ts
  packages/core/src/utils/editCorrector.test.ts
  packages/core/src/utils/editCorrector.ts
  packages/core/src/utils/messageInspectors.ts
Labels: kind/bug, priority/p1, area/core, area/tools, area/memory, status/need-issue

#3060 Update README.md to show API key usage for Vertex
  README.md
Labels: status/need-issue

#2919 fix(cli): Prevent Tab from auto-executing incomplete slash commands
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: status/need-issue

#3469 refactor: rename allowed_mcp_server_names to allowed-mcp-server-names
  GEMINI.md
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#3175 feature(commands) - Refactor Slash Command + Vision For the Future
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/test-utils/mockCommandContext.test.ts
  packages/cli/src/test-utils/mockCommandContext.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/commands/clearCommand.test.ts
  packages/cli/src/ui/commands/clearCommand.ts
  packages/cli/src/ui/commands/helpCommand.test.ts
  packages/cli/src/ui/commands/helpCommand.ts
  packages/cli/src/ui/commands/memoryCommand.test.ts
  packages/cli/src/ui/commands/memoryCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/components/Help.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/contexts/SessionContext.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useCompletion.integration.test.ts
  packages/cli/src/ui/hooks/useCompletion.ts
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/cli/src/ui/types.ts
  packages/core/src/config/config.test.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement

#3483 Initialize MCP tools once at start up instead of every time we auth.
  packages/cli/src/gemini.tsx
  packages/core/src/code_assist/converter.ts
  packages/core/src/config/config.ts
  packages/core/src/core/contentGenerator.ts
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/tool-registry.ts
  packages/core/src/tools/write-file.ts
Labels: kind/bug, area/auth, priority/p1, status/need-information, area/core, area/performance

#3506 Fix infinite loop in start.js on Windows
  scripts/sandbox_command.js
Labels: status/need-issue

#3511 Fix nightly Release
  .github/workflows/release.yml
  packages/cli/tsconfig.json
Labels: status/need-issue

#2881 Improve Function Call argument validation and typing
  package-lock.json
  packages/core/package.json
  packages/core/src/tools/edit.ts
  packages/core/src/tools/glob.test.ts
  packages/core/src/tools/glob.ts
  packages/core/src/tools/grep.test.ts
  packages/core/src/tools/grep.ts
  packages/core/src/tools/ls.ts
  packages/core/src/tools/mcp-client.ts
  packages/core/src/tools/mcp-tool.ts
  packages/core/src/tools/memoryTool.ts
  packages/core/src/tools/read-file.test.ts
  packages/core/src/tools/read-file.ts
  packages/core/src/tools/read-many-files.test.ts
  packages/core/src/tools/read-many-files.ts
  packages/core/src/tools/shell.ts
  packages/core/src/tools/tool-registry.test.ts
  packages/core/src/tools/tools.ts
  packages/core/src/tools/web-fetch.ts
  packages/core/src/tools/web-search.ts
  packages/core/src/tools/write-file.ts
  packages/core/src/utils/schemaValidator.ts
Labels: priority/p3, area/mcp, kind/cleanup

#1381 Improve auth env var validation logic and messaging to detect settings that confuse GenAI SDK
  docs/cli/authentication.md
  docs/cli/configuration.md
  packages/cli/src/config/auth.test.ts
  packages/cli/src/config/auth.ts
  packages/core/src/code_assist/setup.test.ts
  packages/core/src/code_assist/setup.ts
  packages/core/src/core/contentGenerator.test.ts
  packages/core/src/core/contentGenerator.ts
Labels: kind/bug, area/auth, priority/p1

#3191 Add a command line option to enable and list extensions
  docs/cli/configuration.md
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/core/src/config/config.ts
Labels: kind/enhancement, priority/p2, area/extensions

#3560 fix: Honor DEBUG and CLI_TITLE environment variables
  packages/cli/src/config/config.ts
  packages/cli/src/gemini.tsx
Labels: kind/bug, priority/p1, area/core

#3541 refactor: consolidate all flags to use hyphens (deprecate underscore flags)
  docs/cli/configuration.md
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/config/sandboxConfig.ts
Labels: kind/enhancement, priority/p2, area/core, area/ux

#3568 Fix bad request in model check
  packages/core/src/core/modelCheck.ts
Labels: status/need-issue

#3235 fix(auth): do not blindly default to API key auth
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/components/AuthDialog.test.tsx
  packages/cli/src/ui/components/AuthDialog.tsx
Labels: kind/bug, area/auth, priority/p0

#3610 fix(deps): revert yargs bump and fix npx regression
  package-lock.json
  package.json
  packages/cli/package.json
  packages/cli/src/gemini.tsx
  packages/cli/src/nonInteractiveCli.test.ts
  packages/cli/src/nonInteractiveCli.ts
Labels: kind/bug, priority/p0, area/core, area/installation

#3036 Update Terms of Service and Privacy Notice for clarity.
  docs/tos-privacy.md
Labels: kind/bug, priority/p1, area/models, status/need-issue

#3667 mcp-server: Fix debug flag
  docs/tools/mcp-server.md
Labels: status/need-issue

#3662 Remove auto-execution on Flash in the event of a 429/Quota failover
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/cli/src/ui/utils/errorParsing.test.ts
  packages/cli/src/ui/utils/errorParsing.ts
  packages/core/src/code_assist/server.ts
  packages/core/src/config/config.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
  packages/core/src/utils/editCorrector.test.ts
  packages/core/src/utils/quotaErrorDetection.ts
  packages/core/src/utils/retry.ts
Labels: kind/bug, area/GCA, area/auth, priority/p0

#3600 Use yargs array type for the allowedMcpServerNames flag instead of processing the list directly ourselves.
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#3039 Adding TurnId to Tool call and API responses and error logs.
  packages/cli/src/gemini.tsx
  packages/cli/src/nonInteractiveCli.test.ts
  packages/cli/src/nonInteractiveCli.ts
  packages/cli/src/ui/components/ModelStatsDisplay.test.tsx
  packages/cli/src/ui/components/SessionSummaryDisplay.test.tsx
  packages/cli/src/ui/components/StatsDisplay.test.tsx
  packages/cli/src/ui/components/ToolStatsDisplay.test.tsx
  packages/cli/src/ui/contexts/SessionContext.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
  packages/core/src/core/nonInteractiveToolExecutor.test.ts
  packages/core/src/core/nonInteractiveToolExecutor.ts
  packages/core/src/core/turn.test.ts
  packages/core/src/core/turn.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts
  packages/core/src/telemetry/loggers.test.ts
  packages/core/src/telemetry/types.ts
  packages/core/src/telemetry/uiTelemetry.test.ts
Labels: status/need-issue

#3498 Add system-wide settings config for administrators
  docs/cli/configuration.md
  packages/cli/src/config/config.ts
  packages/cli/src/config/settings.test.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/gemini.test.tsx
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/components/AuthDialog.test.tsx
  packages/cli/src/ui/components/ThemeDialog.tsx
  packages/nofrills-cli/demo.txt
Labels: kind/bug, kind/enhancement, area/auth, priority/p1

#3620 fix: Use Email for Clearcut Logging and Refactor User Info Fetching
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/utils/user_id.test.ts
  packages/core/src/utils/user_id.ts
Labels: kind/bug, kind/enhancement, good first issue, area/auth, priority/p2, area/ux

#3672 Fix invalid docker command and invalid JSON in the mcpServers example.
  docs/cli/configuration.md
Labels: kind/bug, kind/documentation, priority/p2, area/core

#2476 Work around bracketed paste support for node < 20
  packages/cli/src/ui/hooks/useKeypress.test.ts
  packages/cli/src/ui/hooks/useKeypress.ts
Labels: kind/bug, priority/p2, area/core, area/ux

#3380 docs: Include video and audio in multi-file tool documentation
  docs/tools/multi-file.md
Labels: kind/bug, priority/p1, area/core

#3042 Update authentication.md to show how to use API keys in GCP
  docs/cli/authentication.md
Labels: status/need-issue

#3745 Summarize tool call outputs using tool specific summarizers
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/core/src/core/client.ts
  packages/core/src/core/coreToolScheduler.ts
  packages/core/src/core/nonInteractiveToolExecutor.ts
  packages/core/src/tools/shell.ts
  packages/core/src/tools/tool-registry.ts
  packages/core/src/tools/tools.ts
  packages/core/src/utils/summarizer.test.ts
  packages/core/src/utils/summarizer.ts
Labels: status/need-issue

#2987 chore: pin GitHub Actions to SHAs
  .github/workflows/ci.yml
  .github/workflows/community-report.yml
  .github/workflows/e2e.yml
  .github/workflows/gemini-automated-issue-triage.yml
  .github/workflows/gemini-scheduled-issue-triage.yml
  .github/workflows/gemini-scheduled-pr-triage.yml
  .github/workflows/release.yml
Labels: kind/bug, kind/enhancement, priority/p2, area/ux

#3795 Logs the auth type in the user prompts, api responses and errors
  docs/telemetry.md
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/core/geminiChat.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts
  packages/core/src/telemetry/loggers.test.ts
  packages/core/src/telemetry/types.ts
Labels: kind/enhancement, area/auth, priority/p2, area/core

#3791 update /theme to new slash command arch
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/ui/commands/themeCommand.test.ts
  packages/cli/src/ui/commands/themeCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
Labels: status/need-issue

#3916 Add oauth test
  packages/core/src/code_assist/oauth2.test.ts
Labels: status/need-issue

#3914 fix: `TypeError: Cannot read properties of undefined (reading 'authType')`
  packages/cli/src/gemini.tsx
  packages/cli/src/nonInteractiveCli.ts
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/core/geminiChat.ts
  packages/core/src/telemetry/types.ts
Labels: kind/bug, priority/p2, area/core

#3843 Adds Flash Fallback logging and clearcut logging
  docs/telemetry.md
  packages/cli/src/ui/App.tsx
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/constants.ts
  packages/core/src/telemetry/index.ts
  packages/core/src/telemetry/loggers.test.ts
  packages/core/src/telemetry/loggers.ts
  packages/core/src/telemetry/types.ts
Labels: kind/enhancement, priority/p2, area/core

#3943 Fix extra whitespace in markdown rendering.
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.tsx
  packages/cli/src/ui/utils/__snapshots__/MarkdownDisplay.test.tsx.snap
Labels: kind/bug, priority/p1, area/ux

#1580 feat: Add clipboard image paste support for macOS
  .gitignore
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/utils/clipboardUtils.test.ts
  packages/cli/src/ui/utils/clipboardUtils.ts
Labels: kind/enhancement, priority/p2, area/tools

#3985 fix(auth): Remove sharp edges from headless auth
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/ConsolePatcher.tsx
  packages/cli/src/ui/hooks/useAuthCommand.ts
  packages/cli/src/ui/utils/ConsolePatcher.ts
  packages/cli/src/utils/cleanup.ts
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
Labels: kind/bug

#4006 feat: Invert scroll arrow default in RadioButtonSelect
  packages/cli/src/ui/components/ThemeDialog.tsx
  packages/cli/src/ui/components/shared/RadioButtonSelect.tsx
Labels: kind/enhancement, priority/p2, area/ux

#4009 feat(tools): Centralize shell tool summarization
  packages/core/src/core/coreToolScheduler.ts
  packages/core/src/core/nonInteractiveToolExecutor.ts
  packages/core/src/tools/shell.test.ts
  packages/core/src/tools/shell.ts
  packages/core/src/tools/tool-registry.ts
  packages/core/src/tools/tools.ts
Labels: kind/bug, priority/p1, area/tools

#4016 Fix not using flash for next speaker check
  packages/core/src/utils/nextSpeakerChecker.test.ts
  packages/core/src/utils/nextSpeakerChecker.ts
Labels: status/need-issue

#4023 chore(release): v0.1.12
  package-lock.json
  package.json
  packages/cli/package.json
  packages/core/package.json
Labels: status/need-issue

#4064 Add back support for escaping newline with a \ character
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: kind/bug, kind/enhancement, priority/p2, area/core

#4092 Fix duplicate help text for build targets in Makefile
  Makefile
Labels: kind/documentation, kind/enhancement, good first issue, priority/p2, area/core

#4051 Add documentation for the /extensions command
  docs/cli/commands.md
Labels: kind/enhancement, priority/p2, area/extensions

#3917 Introduce VSCode companion extension
  eslint.config.js
  package-lock.json
  packages/vscode-ide-companion/.vscode/launch.json
  packages/vscode-ide-companion/.vscode/tasks.json
  packages/vscode-ide-companion/README.md
  packages/vscode-ide-companion/esbuild.js
  packages/vscode-ide-companion/eslint.config.mjs
  packages/vscode-ide-companion/package-lock.json
  packages/vscode-ide-companion/package.json
  packages/vscode-ide-companion/src/extension.ts
  packages/vscode-ide-companion/src/ide-server.ts
  packages/vscode-ide-companion/tsconfig.json
Labels: kind/enhancement, priority/p2, sub-area/extensions, sub-area/ecosystem

#4150 Fix circular reference JSON serialization in telemetry logging
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/integration.test.circular.ts
  packages/core/src/telemetry/loggers.test.circular.ts
  packages/core/src/telemetry/loggers.ts
  packages/core/src/utils/quotaErrorDetection.ts
  packages/core/src/utils/safeJsonStringify.test.ts
  packages/core/src/utils/safeJsonStringify.ts
Labels: kind/bug, sub-area/windows, priority/p0, sub-area/proxy

#4202 Migrate /privacy to new architecture
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/ui/commands/privacyCommand.test.ts
  packages/cli/src/ui/commands/privacyCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
Labels: status/need-issue

#4163 Pure refactor: Consolidate isWithinRoot() function calling.
  packages/core/src/config/config.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/glob.test.ts
  packages/core/src/tools/glob.ts
  packages/core/src/tools/grep.test.ts
  packages/core/src/tools/grep.ts
  packages/core/src/tools/ls.ts
  packages/core/src/tools/read-file.test.ts
  packages/core/src/tools/read-file.ts
  packages/core/src/tools/read-many-files.test.ts
  packages/core/src/tools/read-many-files.ts
  packages/core/src/tools/write-file.ts
  packages/core/src/utils/fileUtils.ts
Labels: kind/enhancement, area/tools

#3759 Update to yargs v18
  esbuild.config.js
  package-lock.json
  package.json
  packages/cli/package.json
Labels: kind/bug, priority/p0, area/core, sub-area/installation

#2763 Fix: Standardize capitalization for "Troubleshooting Guide" in README
  README.md
Labels: kind/bug, kind/documentation, priority/p3

#4154 Adds the user's active file in the IDE to the footer
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/ui/components/Footer.tsx
  packages/core/src/index.ts
  packages/core/src/services/ideContext.test.ts
  packages/core/src/services/ideContext.ts
  packages/core/src/tools/mcp-client.ts
Labels: kind/enhancement

#4244 Revert Node <20 warning
  packages/cli/src/utils/userStartupWarnings.test.ts
  packages/cli/src/utils/userStartupWarnings.ts
Labels: kind/enhancement, good first issue, priority/p3, area/ux

#4241 Upload VSIX of companion VS Code extension
  packages/vscode-ide-companion/.vscodeignore
  packages/vscode-ide-companion/LICENSE
  packages/vscode-ide-companion/assets/icon.png
  packages/vscode-ide-companion/gemini-cli-vscode-ide-companion-0.0.1.vsix
  packages/vscode-ide-companion/package.json
Labels: kind/enhancement, priority/p2, area/core

#4264 [ide-mode] Thread active file through to system prompt
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/core/prompts.test.ts
  packages/core/src/core/prompts.ts
Labels: kind/enhancement, priority/p2, area/core

#4227 Improve altName completion behavior in slash commands
  packages/cli/src/ui/hooks/useCompletion.integration.test.ts
  packages/cli/src/ui/hooks/useCompletion.test.ts
  packages/cli/src/ui/hooks/useCompletion.ts
Labels: kind/bug, priority/p2, area/ux

#3086 Clarifies that Gemini Code Assist, when offered through the Google De…
  docs/cli/authentication.md
Labels: status/need-issue

#4254 Include companion VS Code extension VSIX as part of build/release
  .gitignore
  packages/vscode-ide-companion/gemini-cli-vscode-ide-companion-0.0.1.vsix
  packages/vscode-ide-companion/package.json
  scripts/build.js
  scripts/clean.js
  scripts/copy_bundle_assets.js
Labels: kind/enhancement, priority/p2, area/core

#4176 fix: update google/genai to v1.9.0 and switch to parametersJsonSchema for MCP related tools
  package-lock.json
  packages/cli/src/ui/commands/mcpCommand.ts
  packages/core/package.json
  packages/core/src/tools/mcp-client.ts
  packages/core/src/tools/mcp-tool.test.ts
  packages/core/src/tools/mcp-tool.ts
  packages/core/src/tools/tools.ts
Labels: kind/bug, status/need-triage

#4311 Minor UX updates for IDE mode
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/core/src/services/ideContext.test.ts
  packages/core/src/services/ideContext.ts
  packages/core/src/tools/mcp-client.ts
Labels: kind/enhancement, kind/parent-issue

#4331 Minor refactoring of IDE companion server
  packages/vscode-ide-companion/src/extension.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: kind/enhancement, priority/p2, sub-area/extensions, kind/parent-issue, sub-area/ecosystem

#4348 Fix resetting loop counts on every other event
  packages/core/src/services/loopDetectionService.test.ts
  packages/core/src/services/loopDetectionService.ts
Labels: status/need-issue

#4162 bug(ux): update context percentage when /clear command is run
  packages/cli/src/ui/commands/clearCommand.test.ts
  packages/cli/src/ui/commands/clearCommand.ts
  packages/core/src/telemetry/uiTelemetry.test.ts
  packages/core/src/telemetry/uiTelemetry.ts
Labels: kind/bug, area/ux

#4382 Update companionPort not existing to be a warning so the user can still proceed with running /ide install
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
Labels: status/need-issue

#4266 Zed integration
  packages/cli/src/acp/acp.ts
  packages/cli/src/acp/acpPeer.ts
  packages/cli/src/config/config.ts
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/components/messages/ToolMessage.test.tsx
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/core/src/config/config.ts
  packages/core/src/core/client.ts
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/nonInteractiveToolExecutor.test.ts
  packages/core/src/index.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/glob.ts
  packages/core/src/tools/grep.ts
  packages/core/src/tools/ls.ts
  packages/core/src/tools/mcp-tool.ts
  packages/core/src/tools/memoryTool.ts
  packages/core/src/tools/read-file.ts
  packages/core/src/tools/read-many-files.ts
  packages/core/src/tools/shell.ts
  packages/core/src/tools/tool-registry.test.ts
  packages/core/src/tools/tool-registry.ts
  packages/core/src/tools/tools.ts
  packages/core/src/tools/web-fetch.ts
  packages/core/src/tools/web-search.ts
  packages/core/src/tools/write-file.ts
  packages/core/src/utils/retry.ts
Labels: status/need-issue

#4377 Fix #4220: allow up/down arrow to toggle history when only one sugges…
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: kind/bug, good first issue, priority/p1, area/ux

#4296 Update ESLint and related packages to latest versions
  package-lock.json
Labels: status/need-issue

#4388 migrate restore command
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/test-utils/mockCommandContext.ts
  packages/cli/src/ui/commands/restoreCommand.test.ts
  packages/cli/src/ui/commands/restoreCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
Labels: area/core, status/need-issue

#4419 Migrate /corgi
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/test-utils/mockCommandContext.ts
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/commands/corgiCommand.test.ts
  packages/cli/src/ui/commands/corgiCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
Labels: status/need-issue

#4012 feat(ui): hide cursor when terminal is unfocused
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/hooks/useFocus.test.ts
  packages/cli/src/ui/hooks/useFocus.ts
Labels: kind/bug, kind/enhancement, priority/p1, area/ux

#3532 feat(auth): Enhance OAuth callback for robust Docker support
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
Labels: kind/enhancement, area/authentication, priority/p2, sub-area/ecosystem

#4428 (fix): broken releases and e2e workflows
  .gcp/release-docker.yaml
  scripts/build_sandbox.js
Labels: status/need-issue

#4329 [ide-mode] Send ping every 30 seconds to prevent client from closing connection
  packages/vscode-ide-companion/src/ide-server.ts
Labels: kind/bug, priority/p1, sub-area/memory, area/performance

#4459 Use simple name for MCP tools where possible.
  packages/core/src/tools/mcp-client.test.ts
  packages/core/src/tools/mcp-client.ts
  packages/core/src/tools/mcp-tool.test.ts
  packages/core/src/tools/mcp-tool.ts
  packages/core/src/tools/tool-registry.test.ts
  packages/core/src/tools/tool-registry.ts
Labels: status/need-issue

#4470 Display open IDE file in context section above input box rather than in the footer
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/ContextSummaryDisplay.tsx
  packages/cli/src/ui/components/Footer.tsx
Labels: kind/bug, kind/enhancement, priority/p1, area/core

#4407 Add /background commands (when background agent is configured)
  packages/cli/src/config/config.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/commands/backgroundCommand.ts
  packages/core/src/background/backgroundAgent.ts
  packages/core/src/background/backgroundManager.ts
  packages/core/src/background/types.ts
  packages/core/src/config/config.ts
  packages/core/src/index.ts
  packages/core/src/tools/mcp-tool.ts
Labels: kind/enhancement, priority/p2, area/core, area/tools

#4475 Automatically detect non-interactive environments and fall back to a manual, code-based authentication flow
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/hooks/useAuthCommand.ts
  packages/core/src/code_assist/oauth2.test.ts
  packages/core/src/code_assist/oauth2.ts
  packages/core/src/index.ts
  packages/core/src/utils/browser.ts
Labels: area/authentication, status/need-information

#4469 Make shell output consistent.
  packages/cli/src/ui/components/messages/ToolGroupMessage.tsx
  packages/cli/src/ui/constants.ts
  packages/cli/src/ui/hooks/shellCommandProcessor.test.ts
  packages/cli/src/ui/hooks/shellCommandProcessor.ts
Labels: kind/bug, priority/p2, area/core, area/ux

#3417 fix: prevent RangeError in GitIgnoreParser for root paths
  packages/core/src/utils/gitIgnoreParser.test.ts
  packages/core/src/utils/gitIgnoreParser.ts
Labels: kind/bug, priority/p2, area/core, sub-area/OS-support

#3706 feat: Added /copy command for copying output to clipboard with new Command Service approach
  docs/cli/commands.md
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/ui/commands/copyCommand.test.ts
  packages/cli/src/ui/commands/copyCommand.ts
  packages/cli/src/ui/utils/commandUtils.test.ts
  packages/cli/src/ui/utils/commandUtils.ts
Labels: kind/enhancement

#3680 Check for zeditor if zed binary is not found
  packages/core/src/utils/editor.test.ts
  packages/core/src/utils/editor.ts
Labels: kind/bug, priority/p2, area/core, area/ux

#4511 prefactor(commands): Command Service Prefactor for Extensible Commands
  packages/cli/src/services/BuiltinCommandLoader.test.ts
  packages/cli/src/services/BuiltinCommandLoader.ts
  packages/cli/src/services/CommandService.test.ts
  packages/cli/src/services/CommandService.ts
  packages/cli/src/services/types.ts
  packages/cli/src/ui/commands/aboutCommand.ts
  packages/cli/src/ui/commands/authCommand.ts
  packages/cli/src/ui/commands/bugCommand.ts
  packages/cli/src/ui/commands/chatCommand.ts
  packages/cli/src/ui/commands/clearCommand.ts
  packages/cli/src/ui/commands/compressCommand.ts
  packages/cli/src/ui/commands/copyCommand.ts
  packages/cli/src/ui/commands/corgiCommand.ts
  packages/cli/src/ui/commands/docsCommand.ts
  packages/cli/src/ui/commands/editorCommand.ts
  packages/cli/src/ui/commands/extensionsCommand.ts
  packages/cli/src/ui/commands/helpCommand.test.ts
  packages/cli/src/ui/commands/helpCommand.ts
  packages/cli/src/ui/commands/ideCommand.ts
  packages/cli/src/ui/commands/mcpCommand.ts
  packages/cli/src/ui/commands/memoryCommand.ts
  packages/cli/src/ui/commands/privacyCommand.ts
  packages/cli/src/ui/commands/quitCommand.ts
  packages/cli/src/ui/commands/restoreCommand.ts
  packages/cli/src/ui/commands/statsCommand.ts
  packages/cli/src/ui/commands/themeCommand.ts
  packages/cli/src/ui/commands/toolsCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/components/Help.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useCompletion.integration.test.ts
  packages/cli/src/ui/hooks/useCompletion.test.ts
  packages/cli/src/ui/hooks/useCompletion.ts
Labels: kind/enhancement, community: for-discussion

#4542 feat(cli): add warnings when gemini-cli is called in the root directory
  packages/cli/src/utils/userStartupWarnings.test.ts
  packages/cli/src/utils/userStartupWarnings.ts
Labels: sub-area/privacy, priority/p2

#3501 build(deps): Add missing `resolved` and `integrity` for all dependencies
  package-lock.json
Labels: kind/bug, kind/enhancement, priority/p2, area/ux

#3409 docs: add documentation for mcp excludeTools and includeTools
  docs/cli/configuration.md
  docs/tools/mcp-server.md
Labels: status/need-issue

#3288 feat: Make file type detection and binary checks asynchronous (#3286)
  packages/core/src/tools/read-many-files.ts
  packages/core/src/utils/fileUtils.test.ts
  packages/core/src/utils/fileUtils.ts
Labels: kind/enhancement, priority/p1, area/core, sub-area/performance, kind/issue-triage

#4463 [ide-mode] Keep track of recently-opened files and send them to the CLI
  package-lock.json
  packages/core/src/services/ideContext.ts
  packages/vscode-ide-companion/package.json
  packages/vscode-ide-companion/src/extension.ts
  packages/vscode-ide-companion/src/ide-server.ts
  packages/vscode-ide-companion/src/recent-files-manager.test.ts
  packages/vscode-ide-companion/src/recent-files-manager.ts
  packages/vscode-ide-companion/tsconfig.json
Labels: kind/enhancement, priority/p2, sub-area/mcp, sub-area/extensions

#4458 fix: handle cross-device issues with running otel collector
  scripts/telemetry_utils.js
Labels: kind/bug, priority/p2, area/core, area/platform

#3520 feat(edit): Prevent no-op edits
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
Labels: kind/bug, priority/p1, area/tools, kind/parent-issue, kind/issue-triage

#1949 fix: character encoding issues in shell command processor
  package-lock.json
  packages/cli/src/ui/hooks/shellCommandProcessor.test.ts
  packages/cli/src/ui/hooks/shellCommandProcessor.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/utils/systemEncoding.test.ts
  packages/core/src/utils/systemEncoding.ts
Labels: kind/bug, priority/p2, area/ux

#4422 feat(ci): run e2e tests on macos during ci
  .github/workflows/e2e.yml
Labels: help wanted, sub-area/testing, area/contribution, maintainer

#4634 Fix windows bugs + refactor tests.
  packages/core/src/utils/getFolderStructure.test.ts
  packages/core/src/utils/getFolderStructure.ts
Labels: help wanted, sub-area/testing, area/contribution, maintainer

#2004 add notes on API keys and .gemini/.env to authentication.md
  docs/cli/authentication.md
Labels: status/need-issue

#4575 feat(core): add partUtils module with unit tests
  packages/core/src/core/geminiRequest.test.ts
  packages/core/src/core/geminiRequest.ts
  packages/core/src/utils/partUtils.test.ts
  packages/core/src/utils/partUtils.ts
  packages/core/src/utils/summarizer.ts
Labels: kind/bug, kind/enhancement, priority/p3, area/core, sub-area/testing, sub-area/installation, area/platform

#4747 Update diff colors
  packages/cli/src/ui/colors.ts
  packages/cli/src/ui/components/ThemeDialog.tsx
  packages/cli/src/ui/components/messages/DiffRenderer.test.tsx
  packages/cli/src/ui/components/messages/DiffRenderer.tsx
  packages/cli/src/ui/themes/ansi-light.ts
  packages/cli/src/ui/themes/ansi.ts
  packages/cli/src/ui/themes/atom-one-dark.ts
  packages/cli/src/ui/themes/ayu-light.ts
  packages/cli/src/ui/themes/ayu.ts
  packages/cli/src/ui/themes/dracula.ts
  packages/cli/src/ui/themes/github-dark.ts
  packages/cli/src/ui/themes/github-light.ts
  packages/cli/src/ui/themes/googlecode.ts
  packages/cli/src/ui/themes/no-color.ts
  packages/cli/src/ui/themes/shades-of-purple.ts
  packages/cli/src/ui/themes/theme-manager.test.ts
  packages/cli/src/ui/themes/theme.ts
  packages/cli/src/ui/themes/xcode.ts
  packages/cli/src/ui/utils/CodeColorizer.tsx
Labels: area/ux

#2203 docs: clarify shell command does not use default shell
  docs/cli/commands.md
Labels: kind/bug, kind/documentation, priority/p3, status/in-review

#4795 Safer Shell command Execution
  esbuild.config.js
  packages/cli/src/ui/components/messages/ToolConfirmationMessage.tsx
  packages/core/src/tools/shell.test.ts
  packages/core/src/tools/shell.ts
  packages/core/src/utils/shell-utils.test.ts
  packages/core/src/utils/shell-utils.ts
Labels: status/need-issue

#3936 Vim mode
  docs/cli/commands.md
  docs/cli/configuration.md
  package-lock.json
  packages/cli/src/config/settings.ts
  packages/cli/src/services/BuiltinCommandLoader.ts
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/commands/vimCommand.ts
  packages/cli/src/ui/components/Footer.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/components/shared/text-buffer.ts
  packages/cli/src/ui/components/shared/vim-buffer-actions.test.ts
  packages/cli/src/ui/components/shared/vim-buffer-actions.ts
  packages/cli/src/ui/contexts/VimModeContext.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useKeypress.ts
  packages/cli/src/ui/hooks/vim.test.ts
  packages/cli/src/ui/hooks/vim.ts
Labels: kind/enhancement, priority/p2, area/ux

#3990 fix(ui): remove extraneous whitespace from startup screen
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/__snapshots__/App.test.tsx.snap
  packages/cli/src/ui/components/Footer.tsx
  packages/cli/src/ui/components/Header.tsx
  packages/cli/src/ui/components/Tips.tsx
Labels: kind/bug, priority/p3, area/ux, area/tools

#4757 Fix so legacy custom themes still load.
  packages/cli/src/ui/themes/theme-manager.ts
  packages/cli/src/ui/themes/theme.test.ts
  packages/cli/src/ui/themes/theme.ts
Labels: kind/bug, priority/p2, area/ux

#1601 refactor(telemetry): enhance flushToClearcut method with retry logic and early return for empty events
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/utils/retry.test.ts
  packages/core/src/utils/retry.ts
Labels: kind/bug, priority/p2, area/quality

#4741 Propagate user_prompt_id to GenerateConentRequest for logging
  packages/core/src/code_assist/converter.test.ts
  packages/core/src/code_assist/converter.ts
  packages/core/src/code_assist/server.test.ts
  packages/core/src/code_assist/server.ts
  packages/core/src/code_assist/setup.test.ts
  packages/core/src/code_assist/setup.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/core/contentGenerator.ts
  packages/core/src/core/geminiChat.test.ts
  packages/core/src/core/geminiChat.ts
Labels: status/need-issue

#2401 feat(chat): Implement /chat delete command
  packages/cli/src/ui/commands/chatCommand.test.ts
  packages/cli/src/ui/commands/chatCommand.ts
  packages/core/src/core/logger.test.ts
  packages/core/src/core/logger.ts
Labels: kind/bug, kind/enhancement, priority/p2, area/core, area/ux

#4686 feat: Add auto update functionality
  packages/cli/src/config/settings.ts
  packages/cli/src/gemini.tsx
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/utils/updateCheck.test.ts
  packages/cli/src/ui/utils/updateCheck.ts
  packages/cli/src/utils/handleAutoUpdate.test.ts
  packages/cli/src/utils/handleAutoUpdate.ts
  packages/cli/src/utils/installationInfo.test.ts
  packages/cli/src/utils/installationInfo.ts
  packages/cli/src/utils/updateEventEmitter.ts
  packages/core/src/index.ts
Labels: kind/enhancement, priority/p2, sub-area/installation, area/platform

#4157 Improve error message for discoverTools function
  packages/core/src/tools/mcp-client.test.ts
  packages/core/src/tools/mcp-client.ts
Labels: kind/enhancement, status/in-progress, priority/p2, sub-area/mcp

#1633 Add emacs support, as per user requests. :)
  packages/cli/src/ui/editors/editorSettingsManager.ts
  packages/core/src/utils/editor.test.ts
  packages/core/src/utils/editor.ts
Labels: kind/enhancement, priority/p3, sub-area/extensions
