Repository google-gemini/gemini-cli, pull requests merged in 2025-08, with the labels that each got.

#2036 feat(sandbox): Add SANDBOX_FLAGS for custom container options
  docs/sandbox.md
  packages/cli/src/utils/sandbox.ts
Labels: kind/bug, priority/p2, sub-area/sandbox, area/platform

#4519 [ide-mode] Add openDiff tool to IDE MCP server
  packages/vscode-ide-companion/package.json
  packages/vscode-ide-companion/src/diff-manager.ts
  packages/vscode-ide-companion/src/extension.ts
  packages/vscode-ide-companion/src/ide-server.ts
Labels: kind/enhancement, priority/p2, area/ux

#3196 fix(start): use absolute path to resolve CLI package
  scripts/start.js
Labels: kind/bug, priority/p2, area/core, kind/issue-triage

#4763 perf(core): implement parallel file processing for 74% performance improvement
  packages/core/src/tools/read-many-files.test.ts
  packages/core/src/tools/read-many-files.ts
Labels: kind/enhancement, priority/p1, area/core, sub-area/performance, kind/issue-triage

#2734 Fix and improve Gemini CLI troubleshooting.md doc
  docs/troubleshooting.md
Labels: status/need-issue

#4482 feat(cli): Allow Exiting Authentication Menu with CTRL+C (SIGINT)
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/AuthInProgress.tsx
Labels: kind/bug, kind/enhancement, good first issue, area/authentication, priority/p2, area/ux

#4453 feat(cli) - enhance input UX with double ESC clear
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: status/need-issue

#4738 feat(ui): add /settings command and UI panel
  packages/cli/src/config/settings.ts
  packages/cli/src/config/settingsSchema.test.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/services/BuiltinCommandLoader.ts
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/commands/settingsCommand.test.ts
  packages/cli/src/ui/commands/settingsCommand.ts
  packages/cli/src/ui/commands/types.ts
  packages/cli/src/ui/components/SettingsDialog.test.tsx
  packages/cli/src/ui/components/SettingsDialog.tsx
  packages/cli/src/ui/components/ThemeDialog.tsx
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.ts
  packages/cli/src/ui/hooks/useSettingsCommand.ts
  packages/cli/src/utils/dialogScopeUtils.ts
  packages/cli/src/utils/settingsUtils.test.ts
  packages/cli/src/utils/settingsUtils.ts
Labels: kind/bug, kind/enhancement, priority/p1, area/core

#2603 ensure sandbox build script is cross-platform
  scripts/build_sandbox.js
Labels: status/need-issue

#4406 feat: Allow combining -p and stdin for prompt input
  packages/cli/src/gemini.tsx
  packages/cli/src/utils/readStdin.ts
Labels: kind/enhancement, priority/p2, area/ux

#6092 Update quota-and-pricing.md to clarify billing
  docs/quota-and-pricing.md
Labels: kind/documentation

#4691 feat(cli): prompt completion
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
  packages/cli/src/ui/hooks/useCommandCompletion.test.ts
  packages/cli/src/ui/hooks/useCommandCompletion.tsx
  packages/cli/src/ui/hooks/usePromptCompletion.ts
  packages/core/index.ts
  packages/core/src/config/config.ts
  packages/core/src/index.ts
Labels: status/need-issue

#6729 fix: Ctrl+E should move to current line end, not buffer end
  packages/cli/src/ui/components/InputPrompt.test.tsx
  packages/cli/src/ui/components/InputPrompt.tsx
Labels: pr-batch-3

#6723 fix(copyCommand): provide friendlier error messages for `/copy` command
  docs/cli/commands.md
  packages/cli/src/ui/commands/copyCommand.test.ts
  packages/cli/src/ui/commands/copyCommand.ts
  packages/cli/src/ui/utils/commandUtils.test.ts
  packages/cli/src/ui/utils/commandUtils.ts
Labels: kind/bug, priority/p2, area/ux

#6779 feat(mcp): Improve MCP prompt argument parsing
  packages/cli/src/services/McpPromptLoader.test.ts
  packages/cli/src/services/McpPromptLoader.ts
Labels: kind/bug, priority/p2, area/core

#6836 bug(core): Fix for "no changes" edits.
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
Labels: kind/bug, priority/p1, area/models, status/need-retesting

#6778 feat(mcp): log include MCP request with error
  packages/core/src/tools/mcp-tool.test.ts
  packages/core/src/tools/mcp-tool.ts
Labels: kind/enhancement, sub-area/mcp, area/tools, maintainer

#2038 fix(cli): Support special characters in sandbox profile path
  packages/cli/src/utils/sandbox.ts
Labels: kind/bug, priority/p2, sub-area/sandbox

#3228 chore(test): install and configure vitest eslint plugin
  eslint.config.js
  package-lock.json
  package.json
  packages/cli/src/config/config.test.ts
  packages/cli/src/ui/components/shared/text-buffer.test.ts
  packages/cli/src/ui/hooks/useGeminiStream.test.tsx
  packages/cli/src/utils/gitUtils.test.ts
  packages/core/src/core/client.test.ts
  packages/core/src/utils/memoryImportProcessor.test.ts
  packages/core/src/utils/retry.test.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#6765 refactor(ide): Improve IDE detection discovery
  docs/ide-integration.md
  integration-tests/ide-client.test.ts
  packages/cli/src/ui/IdeIntegrationNudge.tsx
  packages/cli/src/ui/commands/ideCommand.ts
  packages/cli/src/ui/hooks/slashCommandProcessor.test.ts
  packages/core/src/config/config.ts
  packages/core/src/ide/detect-ide.test.ts
  packages/core/src/ide/detect-ide.ts
  packages/core/src/ide/ide-client.test.ts
  packages/core/src/ide/ide-client.ts
  packages/core/src/ide/process-utils.test.ts
  packages/core/src/ide/process-utils.ts
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
Labels: kind/enhancement, sub-area/extensions, area/extensibility

#3033 fix(core): enable thinking explicitly in flash-lite models
  packages/core/src/core/client.ts
Labels: kind/bug, priority/p1, area/models, kind/issue-triage

#2934 Downgrade branch_protection to `log`
  .allstar/branch_protection.yaml
Labels: kind/enhancement, sub-area/allstar, sub-area/GCA, priority/p3, status/need-information, allstar, area/security-privacy

#6453 feat(cli): Add --allowed-tools flag to bypass tool confirmation (#2417)
  docs/cli/configuration.md
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/cli/src/ui/hooks/useToolScheduler.test.ts
  packages/core/src/config/config.test.ts
  packages/core/src/config/config.ts
  packages/core/src/core/coreToolScheduler.test.ts
  packages/core/src/core/coreToolScheduler.ts
  packages/core/src/core/nonInteractiveToolExecutor.test.ts
  packages/core/src/tools/tools.ts
  packages/core/src/utils/shell-utils.test.ts
  packages/core/src/utils/shell-utils.ts
  packages/core/src/utils/tool-utils.test.ts
  packages/core/src/utils/tool-utils.ts
Labels: status/need-issue

#5819 feat(subagent): Enable incremental output streaming
  packages/core/src/core/subagent.test.ts
  packages/core/src/core/subagent.ts
Labels: status/need-issue

#6081 fix(core): treat UTF16/32 BOM files as text and decode correctly
  integration-tests/utf-bom-encoding.test.ts
  packages/core/src/utils/fileUtils.test.ts
  packages/core/src/utils/fileUtils.ts
Labels: kind/bug, good first issue, sub-area/windows, priority/p1, area/core, area/tools

#4652 fix: add flash lite with respect to api defaults
  packages/core/src/config/models.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#5336 Restore missing `resolved` and `integrity` of some dependencies and add check of lockfile integrity
  .github/workflows/ci.yml
  package-lock.json
  package.json
  scripts/check-lockfile.js
Labels: kind/bug, kind/enhancement, priority/p2, area/ux

#7321 Add flag to update all extensions
  packages/cli/src/commands/extensions/update.ts
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
Labels: kind/bug, area/models, sub-area/extensions, maintainer

#6662 fix(core): Fix permissions for oauth_creds.json
  packages/core/src/code_assist/oauth2.ts
Labels: kind/bug, priority/p2, sub-area/security

#7213 feat(extension): resolve environment variables in extension configuration
  packages/cli/src/config/extension.test.ts
  packages/cli/src/config/extension.ts
  packages/cli/src/config/settings.ts
  packages/cli/src/utils/envVarResolver.test.ts
  packages/cli/src/utils/envVarResolver.ts
Labels: kind/bug, priority/p2

#7409 fix(trust): Respect folder trust setting when reading GEMINI.md
  packages/a2a-server/src/config.ts
  packages/cli/src/config/config.test.ts
  packages/cli/src/config/config.ts
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/commands/directoryCommand.tsx
  packages/cli/src/ui/commands/memoryCommand.test.ts
  packages/cli/src/ui/commands/memoryCommand.ts
  packages/core/src/config/config.ts
  packages/core/src/utils/memoryDiscovery.test.ts
  packages/core/src/utils/memoryDiscovery.ts
Labels: status/need-issue

#5890 fix(cli): preserve input history after /clear command
  packages/cli/src/ui/App.test.tsx
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/hooks/useInputHistoryStore.test.ts
  packages/cli/src/ui/hooks/useInputHistoryStore.ts
Labels: kind/bug, priority/p1, area/contribution, status/need-retesting

#6633 feat(cli): add fuzzy matching for command suggestions
  packages/cli/src/ui/hooks/useSlashCompletion.test.ts
  packages/cli/src/ui/hooks/useSlashCompletion.ts
Labels: kind/bug, priority/p2, area/ux

#2691 refactor: remove redundant 'undefined' type or '?'
  packages/cli/src/ui/components/shared/MaxSizedBox.tsx
  packages/core/src/core/contentGenerator.ts
Labels: status/need-issue

#6823 Smart Edit Tool
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/core/src/config/config.ts
  packages/core/src/tools/smart-edit.test.ts
  packages/core/src/tools/smart-edit.ts
  packages/core/src/utils/llm-edit-fixer.ts
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7449 fix(workflows): improve issue triage
  .github/workflows/gemini-automated-issue-triage.yml
  .github/workflows/gemini-scheduled-issue-triage.yml
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7446 fix(diffstats): Fix diff stats to correctly capture the edits
  packages/core/src/tools/edit.test.ts
  packages/core/src/tools/edit.ts
Labels: kind/bug, priority/p2, area/core

#7486 Update gemini-automated-issue-triage.yml
  .github/workflows/gemini-automated-issue-triage.yml
  .github/workflows/gemini-scheduled-issue-triage.yml
Labels: kind/enhancement, priority/p1, area/models, status/need-retesting

#7483 Fix duplicate LOC counting due to diff_stat being passed in multiple places
  packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts
  packages/core/src/telemetry/loggers.ts
  packages/core/src/telemetry/metrics.test.ts
  packages/core/src/telemetry/metrics.ts
  packages/core/src/telemetry/types.ts
  packages/core/src/tools/edit.ts
  packages/core/src/tools/read-file.ts
  packages/core/src/tools/read-many-files.ts
  packages/core/src/tools/write-file.ts
Labels: kind/bug, priority/p2, area/core

#7502 fix(auth): Fix failing auth test
  packages/cli/src/config/auth.test.ts
Labels: status/need-issue

#7514 fix(release) - make release failures p0
  .github/workflows/release.yml
Labels: status/need-issue
